name: Close Issue and Handle PR

on:
  issues:
    types: [closed]

jobs:
  close-issue-and-handle-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install @octokit/rest @actions/github uuid

      - name: Handle Closed Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node .github/scripts/closeIssueAndHandlePR.mjs
