name: Issue to Pull Request

on:
  issues:
    types: [opened, edited]

jobs:
  convert-issue-to-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install octokit
      run: npm install @octokit/rest

    - name: Convert Issue to Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: node .github/scripts/convertIssueToPR.js
