name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'paths/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install @octokit/rest marked

    - name: Generate structure.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: node .github/scripts/fetchStructure.js

    - name: Generate HTML files
      run: node .github/scripts/generateHtmlFiles.js

    - name: Generate index.html
      run: node .github/scripts/generateIndex.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
